#!/bin/sh
# Tag and push a release.
set -e

cd $(dirname "$0")/..

bundle update

(git branch | grep -q 'master') || {
  echo "Only release from the master branch."
  exit 1
}

echo "Add a tag number eg. 0.1"
read VER
tag=v$VER

#git fetch -t origin

(git tag -l | grep -q "$tag") && {
  echo "Whoops, there's already a '${tag}' tag."
  exit 1
}
	
git tag "$tag"  && git push origin master && git push origin "$tag"
